### PR TITLE
Add image carousel to homepage

### PR DESCRIPTION
**Pull request by gsbaker**
Screenshot 2021-10-10 at 13 40 15

# Changes
* Add image carousel to homepage
* Images are sourced from [Unsplash](https://unsplash.com)

My plan is to showcase different images every month. E.g. we could do pride month, Apple Park, etc.

### CODE REVIEW

**Comment by gsbaker** [comment]
Thoughts @jontyrudman ?

**Comment by gsbaker** [comment]
> I like it! Is there any reason not to just set the first image as active in the template instead of having an extra single-use key in the YAML?

Yes, because it means no images need to be hardcoded. I tried it both ways and decided it would be easier to keep it all in YAML

**Comment by jontyrudman** [comment]
I'm not sure we understand each other here. To be clear, I'm talking purely about the use of the `active` keyword, the photo paths should definitely be kept in the YAML. Why not just use a counter in the loop in the template and replace `{% if image.active %}` with something checking whether it's the first image?

**Comment by gsbaker** [comment]
> I'm not sure we understand each other here. To be clear, I'm talking purely about the use of the `active` keyword, the photo paths should definitely be kept in the YAML. Why not just use a counter in the loop in the template and replace `{% if image.active %}` with something checking whether it's the first image?

Are you suggesting something like this?
```
flag = True
for ....
if flag
   # active div
flag = false
```

**Comment by gsbaker** [comment]
@jontyrudman I've changed it to how I think you meant.

**Review by jontyrudman — APPROVED** [review]

**Comment by jontyrudman** [comment]
And FYI I left this free for you to merge as you see fit, using list index or as-is. @gsbaker

**Pull request merged**
